/*
 * Manual_Mode.c
 *
 *  Created on: Mar 26, 2020
 *      Author: Athishay
 *
 *
 */
/* USER CODE BEGIN Includes */
#include "main.h"
#include "gpio.h"
/* USER CODE END Includes */

/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

void Run_ManualMode(void)
{
	// Manual control for Unit1

	/*if(HAL_GPIO_ReadPin(PEDAL_A1_GPIO_Port, PEDAL_A1_Pin) && !HAL_GPIO_ReadPin(PEDAL_A2_GPIO_Port, PEDAL_A2_Pin))
		{
			HAL_GPIO_WritePin(LD1_GPIO_Port, LD1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(LD3_GPIO_Port, LD3_Pin, GPIO_PIN_SET);
		}
		else
		{
			HAL_GPIO_WritePin(LD1_GPIO_Port, LD1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(LD3_GPIO_Port, LD3_Pin, GPIO_PIN_RESET);
		}*/
	if(HAL_GPIO_ReadPin(PEDAL_A1_GPIO_Port, PEDAL_A1_Pin) && !HAL_GPIO_ReadPin(PEDAL_A2_GPIO_Port, PEDAL_A2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_1R_GPIO_Port, CYLINDER_1R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_1F_GPIO_Port, CYLINDER_1F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_1R_GPIO_Port, CYLINDER_1R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_1F_GPIO_Port, CYLINDER_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_RESET);
	}
	if(!HAL_GPIO_ReadPin(PEDAL_A1_GPIO_Port, PEDAL_A1_Pin) && HAL_GPIO_ReadPin(PEDAL_A2_GPIO_Port, PEDAL_A2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_1R_GPIO_Port, CYLINDER_1R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(CYLINDER_1F_GPIO_Port, CYLINDER_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_1R_GPIO_Port, CYLINDER_1R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_1F_GPIO_Port, CYLINDER_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_RESET);
	}

	// Manual control for Unit2
	if(HAL_GPIO_ReadPin(PEDAL_B1_GPIO_Port, PEDAL_B1_Pin) && !HAL_GPIO_ReadPin(PEDAL_B2_GPIO_Port, PEDAL_B2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_2R_GPIO_Port, CYLINDER_2R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_2F_GPIO_Port, CYLINDER_2F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_2R_GPIO_Port, CYLINDER_2R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_2F_GPIO_Port, CYLINDER_2F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_RESET);
	}
	if(!HAL_GPIO_ReadPin(PEDAL_B1_GPIO_Port, PEDAL_B1_Pin) && HAL_GPIO_ReadPin(PEDAL_B2_GPIO_Port, PEDAL_B2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_2R_GPIO_Port, CYLINDER_2R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(CYLINDER_2F_GPIO_Port, CYLINDER_2F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_2R_GPIO_Port, CYLINDER_2R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_2F_GPIO_Port, CYLINDER_2F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_RESET);
	}


	// Manual control for Unit3
	if(HAL_GPIO_ReadPin(PEDAL_C1_GPIO_Port, PEDAL_C1_Pin) && !HAL_GPIO_ReadPin(PEDAL_C2_GPIO_Port, PEDAL_C2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_3R_GPIO_Port, CYLINDER_3R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_3F_GPIO_Port, CYLINDER_3F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_3R_GPIO_Port, CYLINDER_3R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_3F_GPIO_Port, CYLINDER_3F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_RESET);
	}
	if(!HAL_GPIO_ReadPin(PEDAL_C1_GPIO_Port, PEDAL_C1_Pin) && HAL_GPIO_ReadPin(PEDAL_C2_GPIO_Port, PEDAL_C2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_3R_GPIO_Port, CYLINDER_3R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(CYLINDER_3F_GPIO_Port, CYLINDER_3F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_3R_GPIO_Port, CYLINDER_3R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_3F_GPIO_Port, CYLINDER_3F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_1_GPIO_Port, MOTOR_1_Pin, GPIO_PIN_RESET);
	}

	// Manual control for Unit4
	if(HAL_GPIO_ReadPin(PEDAL_D1_GPIO_Port, PEDAL_D1_Pin) && !HAL_GPIO_ReadPin(PEDAL_D2_GPIO_Port, PEDAL_D2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_4R_GPIO_Port, CYLINDER_4R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_4F_GPIO_Port, CYLINDER_4F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_4R_GPIO_Port, CYLINDER_4R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_4F_GPIO_Port, CYLINDER_4F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_RESET);
	}
	if(!HAL_GPIO_ReadPin(PEDAL_D1_GPIO_Port, PEDAL_D1_Pin) && HAL_GPIO_ReadPin(PEDAL_D2_GPIO_Port, PEDAL_D2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_4R_GPIO_Port, CYLINDER_4R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(CYLINDER_4F_GPIO_Port, CYLINDER_4F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_4R_GPIO_Port, CYLINDER_4R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_4F_GPIO_Port, CYLINDER_4F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_RESET);
	}

	// Manual control for Unit5
	if(HAL_GPIO_ReadPin(PEDAL_E1_GPIO_Port, PEDAL_E1_Pin) && !HAL_GPIO_ReadPin(PEDAL_E2_GPIO_Port, PEDAL_E2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_5R_GPIO_Port, CYLINDER_5R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_5F_GPIO_Port, CYLINDER_5F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_5R_GPIO_Port, CYLINDER_5R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_5F_GPIO_Port, CYLINDER_5F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_RESET);
	}
	if(!HAL_GPIO_ReadPin(PEDAL_E1_GPIO_Port, PEDAL_E1_Pin) && HAL_GPIO_ReadPin(PEDAL_E2_GPIO_Port, PEDAL_E2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_5R_GPIO_Port, CYLINDER_5R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(CYLINDER_5F_GPIO_Port, CYLINDER_5F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_5R_GPIO_Port, CYLINDER_5R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_5F_GPIO_Port, CYLINDER_5F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_RESET);
	}


	// Manual control for Unit6
	if(HAL_GPIO_ReadPin(PEDAL_F1_GPIO_Port, PEDAL_F1_Pin) && !HAL_GPIO_ReadPin(PEDAL_F2_GPIO_Port, PEDAL_F2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_6R_GPIO_Port, CYLINDER_6R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_6F_GPIO_Port, CYLINDER_6F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_6R_GPIO_Port, CYLINDER_6R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_6F_GPIO_Port, CYLINDER_6F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_RESET);
	}
	if(!HAL_GPIO_ReadPin(PEDAL_F1_GPIO_Port, PEDAL_F1_Pin) && HAL_GPIO_ReadPin(PEDAL_F2_GPIO_Port, PEDAL_F2_Pin))
	{
		HAL_GPIO_WritePin(CYLINDER_6R_GPIO_Port, CYLINDER_6R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(CYLINDER_6F_GPIO_Port, CYLINDER_6F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_SET);
	}
	else
	{
		HAL_GPIO_WritePin(CYLINDER_6R_GPIO_Port, CYLINDER_6R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(CYLINDER_6F_GPIO_Port, CYLINDER_6F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_2_GPIO_Port, MOTOR_2_Pin, GPIO_PIN_RESET);
	}
}

/* USER CODE END 0 */
